version: '3'

services:
  suggestedtracks:
    image: sts
    build: .
    environment:
      NODE_ENV: production
    depends_on:
      - 'database'
    ports: 
      - '4001:4001'

  database:
    image: mongo:latest
